version: "3.7"

services:
  database: 
    container_name: database
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: P1234p
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: clarusway
      MYSQL_PASSWORD: Clarusway_1
    networks:
      - clarusnet

  myapp:
    container_name: myapp
    image: mrbaykal/book-store-api:latest
    restart: always
    depends_on:
      - database
    ports:
      - 80:80
    networks:
      - clarusnet


networks:
  clarusnet:



